apiVersion: v1
kind: Service
metadata:
  name: timestamper-svc
  labels:
    app: timestamper
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: timestamper
